name: Code check
on:
  pull_request:
  push:
      branches:
        - main
jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/dev.txt --upgrade pip
      - name: Create fake config.toml file
        run: cp config.toml.template config.toml
      - name: Run codecheck
        run: bash scripts/codecheck.sh
